### ISSUE TITLE
FIDO registration fails for TPM Infineon SLB9670

### ISSUE THREAD

**Issue by rzvpopescu** [passwordless-lib/fido2-net-lib#236]
I'm trying to register a HP Elitebook 850 G8 (TPM Infineon SLB9670) but fails for some reasons with error :
`"Unhandled exception: wrong number of sub-elements: 3 (expected: 1)"`

Here is the stack trace
```
StackTrace
at Asn1.AsnElt.CheckNumSub(Int32 n)
   at Fido2NetLib.AttestationFormat.Tpm.SANFromAttnCertExts(X509ExtensionCollection exts)
   at Fido2NetLib.AttestationFormat.Tpm.Verify()
   at Fido2NetLib.AuthenticatorAttestationResponse.VerifyAsync(CredentialCreateOptions originalOptions, Fido2Configuration config, IsCredentialIdUniqueToUserAsyncDelegate isCredentialIdUniqueToUser, IMetadataService metadataService, Byte[] requestTokenBindingId)
   at Fido2NetLib.Fido2.MakeNewCredentialAsync(AuthenticatorAttestationRawResponse attestationResponse, CredentialCreateOptions origChallenge, IsCredentialIdUniqueToUserAsyncDelegate isCredentialIdUniqueToUser, Byte[] requestTokenBindingId)
```
Any ideas ?

**Comment by aseigler** [comment]
Sounds like #187.  Are you running an older version?

**Comment by rzvpopescu** [comment]
> Sounds like #187. Are you running an older version?

Yes. But is happening with v 2.0.2 also.

**Comment by aseigler** [comment]
Can you take the steps like we did [here](https://github.com/passwordless-lib/fido2-net-lib/pull/187#issuecomment-689144761) and report the results?

**Comment by rzvpopescu** [comment]
> Can you take the steps like we did [here](https://github.com/passwordless-lib/fido2-net-lib/pull/187#issuecomment-689144761) and report the results?

Here it is:
```

0000: 30 4c                                     ; SEQUENCE (4c Bytes)
0002:    a4 4a                                  ; OPTIONAL[4] (4a Bytes)
0004:       30 48                               ; SEQUENCE (48 Bytes)
0006:          31 16                            ; SET (16 Bytes)
0008:          |  30 14                         ; SEQUENCE (14 Bytes)
000a:          |     06 05                      ; OBJECT_ID (5 Bytes)
000c:          |     |  67 81 05 02 01
               |     |     ; 2.23.133.2.1 TPMManufacturer
0011:          |     0c 0b                      ; UTF8_STRING (b Bytes)
0013:          |        69 64 3a 34 39 34 36 35  38 30 30                 ; id:49465800
               |           ; "id:49465800"
001e:          31 1a                            ; SET (1a Bytes)
0020:          |  30 18                         ; SEQUENCE (18 Bytes)
0022:          |     06 05                      ; OBJECT_ID (5 Bytes)
0024:          |     |  67 81 05 02 02
               |     |     ; 2.23.133.2.2 TPMModel
0029:          |     0c 0f                      ; UTF8_STRING (f Bytes)
002b:          |        53 4c 42 20 39 36 37 30  20 54 50 4d 32 2e 30     ; SLB 9670 TPM2.0
               |           ; "SLB 9670 TPM2.0"
003a:          31 12                            ; SET (12 Bytes)
003c:             30 10                         ; SEQUENCE (10 Bytes)
003e:                06 05                      ; OBJECT_ID (5 Bytes)
0040:                |  67 81 05 02 03
                     |     ; 2.23.133.2.3 TPMVersion
0045:                0c 07                      ; UTF8_STRING (7 Bytes)
0047:                   69 64 3a 30 37 35 35                              ; id:0755
                           ; "id:0755"
```

**Comment by rzvpopescu** [comment]
> Sounds like #187. Are you running an older version?

It is #187 indeed. Thanks for your help and time.
