### ISSUE TITLE
Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by dyzhe** [passwordless-lib/fido2-net-lib#282]
Using Fido2 version 2.0.2
Trying to register Fido2 tokens from TrustKey T110 and G310H.
MakeNewCredentialAsync throws exception "Index was outside the bounds of the array".

**Comment by abergs** [comment]
Do you have any more data, such as callstack?

**Comment by dyzhe** [comment]
The exception I got from MakeNewCredentialAsync 

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Fido2NetLib.Packed.<>c.<IsValidPackedAttnCertSubject>b__0_2(String[] split) in C:\caspeco\github\fido2-net-lib\Src\Fido2\AttestationFormat\Packed.cs:line 32
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Fido2NetLib.Packed.IsValidPackedAttnCertSubject(String attnCertSubj) in C:\caspeco\github\fido2-net-lib\Src\Fido2\AttestationFormat\Packed.cs:line 30
   at Fido2NetLib.Packed.Verify() in C:\caspeco\github\fido2-net-lib\Src\Fido2\AttestationFormat\Packed.cs:line 86
   at Fido2NetLib.AuthenticatorAttestationResponse.<VerifyAsync>d__10.MoveNext() in C:\caspeco\github\fido2-net-lib\Src\Fido2\AuthenticatorAttestationResponse.cs:line 135
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Fido2NetLib.Fido2.<MakeNewCredentialAsync>d__6.MoveNext() in C:\caspeco\github\fido2-net-lib\Src\Fido2\Fido2NetLib.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DebugConsole.Auth.Fido.<TestAsync>d__1.MoveNext() in M:\proj\DebugConsole\DebugConsole\Auth\Fido.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DebugConsole.Program.Main(String[] args) in M:\proj\DebugConsole\DebugConsole\Program.cs:line 65

**Comment by aseigler** [comment]
Which authenticator make/model was used for this? Seems like it has a malformed attestation certificate, but we should handle it more cleanly.

**Comment by aseigler** [comment]
Ok, after investigating, this was previously fixed by #229 and will be included in the upcoming major release.
