### ISSUE TITLE
Error in MakeNewCredentialAsync using Linux with Firefox 114 and above

### ISSUE THREAD

**Issue by dib0** [passwordless-lib/fido2-net-lib#406]
Hi,

I'm using fido2-net-lib (version 3.0.1) in my .Net core (6) application. When I add a credential using my hardware token using Windows and Firefox or Chrome it is working well (didn't test other browsers). When using Linux and Firefox (version 114 and above) the MakeNewCredentialAsync throws an exception:
```
Unable to cast object of type 'Fido2NetLib.Cbor.CborTextString' to type 'Fido2NetLib.Cbor.CborInteger'.', '   at Fido2NetLib.Cbor.CborObject.op_Explicit(CborObject obj)
   at Fido2NetLib.Objects.CredentialPublicKey..ctor(CborMap cpk)
   at Fido2NetLib.Objects.CredentialPublicKey.Decode(ReadOnlyMemory`1 cpk, Int32& bytesRead)
   at Fido2NetLib.Objects.AttestedCredentialData..ctor(ReadOnlyMemory`1 data, Int32& bytesRead)
   at Fido2NetLib.Objects.AuthenticatorData..ctor(Byte[] authData)
   at Fido2NetLib.AuthenticatorAttestationResponse.VerifyAsync(CredentialCreateOptions originalOptions, Fido2Configuration config, IsCredentialIdUniqueToUserAsyncDelegate isCredentialIdUniqueToUser, IMetadataService metadataService, Byte[] requestTokenBindingId, CancellationToken cancellationToken)
   at Fido2NetLib.Fido2.MakeNewCredentialAsync(AuthenticatorAttestationRawResponse attestationResponse, CredentialCreateOptions origChallenge, IsCredentialIdUniqueToUserAsyncDelegate isCredentialIdUniqueToUser, Byte[] requestTokenBindingId, CancellationToken cancellationToken)
```

Am I doing something wrong here? Or is there some issue with Firefox under Linux? 
I just installed Chrome and tested Chrome with Linux, that seems to be working fine as well.

And if a credential is created and saved the authentication works fine, also using Firefox under Linux.

**Comment by aseigler** [comment]
I do not believe this is occurring any longer.  We've re-written the parser since this report.
